package exercise;

class RP_ExceptionEx7 {
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try{
			throw new Exception();
		}catch(Exception e){
			System.out.println("Exception이 발생했습니다.");
		}
		
	}
}
